#@ load("@ytt:data", "data")
#@ load("commons.lib.yaml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: cfroutesync
  namespace: #@ data.values.systemNamespace
  labels: #@ labels()
type: Opaque
stringData:
  clientSecret: #@ data.values.cfroutesync.clientSecret
